name: ballot

ethereum:
  default_network: local
  local:
    default_provider: hardhat

dependencies:
  - name: Solidity-RLP
    github: hamdiallam/Solidity-RLP
    version: v2.0.7
  - name: solmate
    github: transmissions11/solmate
    version: v6
    contracts_folder: src

solidity:
  import_remapping:
    - hamdiallam/Solidity-RLP=Solidity-RLP/v2.0.7
    - transmissions11/solmate=solmate/v6
